### ISSUE TITLE
No avatar mark on search result

### ISSUE THREAD

**Issue by Geist-zz** [brave/goggles-quickstart#13]
I found one case (there could be more) when avatar mark isn't show next to the search result.
Search keyword: `test`
One of the results was a pl.pornhub (NSFW) page, which wasn't marked.

Goggle:
```
$discard

! pl.(wikipedia)
|http://pl.$boost=1
|https://pl.$boost=1
```

**Comment by remusao** [comment]
Hi @Geist-zz,

Thanks for the feedback. The avatars (a.k.a. favicons) you see on each result are fetched asynchronously for cases where we do not have them in our database (while that process is ongoing, you will see a generic image in the form of a globe). It seems like the one you did notice is not available.

Hope that helps,
