### ISSUE TITLE
"How do I use Goggles?" links to old brave-experiments location

### ISSUE THREAD

**Issue by Anteus** [brave/goggles-quickstart#17]
The guide for [Goggles](https://support.brave.com/hc/en-us/articles/6959189556237-How-do-I-use-Goggles-) links to Github [brave-experiments](https://github.com/brave-experiments/goggles-quickstart) instead of just [brave](https://github.com/brave/goggles-quickstart).

>For an in-depth guide on how to create your own custom Goggles, please see this [article provided by Brave Team](https://github.com/brave-experiments/goggles-quickstart).

**Comment by remusao** [comment]
Hi @Anteus,

Thanks for reaching out. We'll get this fixed ASAP! Good catch.

**Comment by Brave-Matt** [comment]
Thanks for the heads up @Anteus! This is now fixed 👍

**Comment by debasmitaconmove** [comment]
How can i use Goggle for ranking our website conmove.io
