### ISSUE TITLE
Behavior of default option values: `inurl`

### ISSUE THREAD

**Issue by devidw** [brave/goggles-quickstart#18]
Quoting the quickstart:

> By default any instruction will apply to a URL

Does this mean that the following are the same?

```
pattern
pattern$inurl
```

Is there a way to don't match URL and for example only the content?

```
pattern$incontent
```

Or is this still equal to:

```
pattern$incontent,inurl
```

**Comment by remusao** [comment]
Hi @devidw,

Thanks for reaching out. It is correct to assume that `pattern` and `pattern$inurl` are the same.

And regarding your second question, `pattern$incontent` is not equivalent to `pattern$incontent,inurl`. We only default to `inurl` context whenever no other context is specified.

Please note that the `incontent` option is not yet implemented in Brave Search, though.

**Comment by devidw** [comment]
Got it, thanks a lot @remusao 🙌

**Comment by devidw** [comment]
The context options, which unset the default `inurl` option, are the `in…` options, right?

Other options like the `site` option are not considered a “context” option in the same manner as the `in…` options, is this correct?

And therefore `pattern$site=…` is still the same as `pattern$site=…,inurl`?

***

So, the options in general could be classified as:

* Action options, e.g. `boost` (action defaults to `boost`, value for `boost` and `downrank` equals to `2`)
* Context options, all `in…`, e.g. `inurl` (default context option is `inurl`, only if no other provided)
* Generic options, e.g. `site`

Please correct me, if I have misunderstood this.

**Comment by remusao** [comment]
This is correct!

**Comment by devidw** [comment]
Thx 🙌
