### ISSUE TITLE
My goggle 

### ISSUE THREAD

**Issue by Itsamejonah** [brave/goggles-quickstart#48]
github.com/Itsamejonah/NoSoftonic
```[tasklist]
### Tasks
- [ ] add it
- [ ] finish
```

**Comment by remusao** [comment]
Hi,

Whenever you want to add your own Goggle, you can submit it on this page: https://search.brave.com/goggles/create
No need to open an issue in this repository unless you find issues or need assistance.

Best,

**Comment by Itsamejonah** [comment]
reopen this this instant
