### ISSUE TITLE
Mistake in quickstart guide

### ISSUE THREAD

**Issue by Fourst8** [brave/goggles-quickstart#6]
https://github.com/brave/goggles-quickstart/blob/75631701ef1d8b298bcf52ffe482f1abf2447f9f/goggles/quickstart.goggle#L93

it says that you can use "$site", but it doesn't actually work, it only works if "site" is used (without the dollar sign).

**Comment by remusao** [comment]
Hi @Fourst8,

Thanks for reaching out. Can you explain why you mean by "it does not work"? Does it mean that the Goggle is rejected upon submission? Or does it mean that the results you get when using it with a query are not what you expected?
